### ISSUE TITLE
Add monsters

### ISSUE THREAD

**Issue by orffen** [DC23/basicfantasyrpg-corerules-en#2]
I know you're working on it already, creating this issue more for tracking progress. Could you create a branch for this so we can sync progress? I may be able to help with some of the data entry.

**Comment by Stew-rt** [comment]
Hey orffen,
I've created the branch of current progress, as requested.
So, I've separated them roughly around the monster index spreadsheet available on the Basic Fantasy site.
I've got all the descriptions in.
I've created tokens for all which have images in the book, using https://rolladvantage.com/tokenstamp/ (using the default token format)
many have default stats, though (usually obvious if the monster has hit point values, as I've been removing them as they are generated on token creation), and there are going to be a fair amount which need additional variations added due to the different hit-dice options.
I believe I've got all (reverse alphabetic, Z-A from the book) until Mummy done..

**Comment by FR4NC35CO** [comment]
Hi there, how far is the monsters' compendium from completion?
Hey you've done an amazing work btw! Love it

**Comment by totallybanjaxed** [comment]
Hey @Stew-rt, just getting to look at the data entry side today.  Looks like all the monster entries are present except for White Dragon (7th Age).  Other than adding that one in, and based on comments above, I just need to find where you left off and set the right stats (and image if possible) yeah?  

I'm still not too experienced with foundry is the easiest way to do this by importing and editing inside a blank BF world and then unlocking the compendium folder and saving back?  That's the way I've done it before because I was told editing the .db files is a general no-no.  However I thought I'd check in case there's an easier way :)

**Comment by Stew-rt** [comment]
I found editing the actors from within the compendium was simpler (so yes, they would need to be unlocked) - as it's harder to make mistakes.
If you need a new actor, just make a new one, and save it into the relevant compendium.
I'm pretty sure there are more missing than that..

Unfortunately I didn't find a better way of doing this.. which is why it took me so long..

**Comment by totallybanjaxed** [comment]
No worries, and thanks for getting back to me.  I pulled the contents of all the monster-*.db files, stripped out the names and popped them into a spreadsheet and then compared against the SRD, and the above was the only one that I didn't see present in that list.  So I think there's definitely an entry for each of the others, but whether they are working or complete etc. I did not check.  

A ton of work has obviously gone into it already, and it must have taken an age.  Hopefully I can add to it or get it further and then see if we can make it available.  Can't promise but I'll put a bit of effort in whenever I can.

**Comment by Stew-rt** [comment]
Thanks so much.. yeah.. it took quite some time to get that far..

**Comment by totallybanjaxed** [comment]
I'm only after noticing this now but in the SRD/book if the monster's Attack Bonus is different than its number of Hit Dice, purely for convenience the Attack Bonus is listed in parentheses after the Hit Dice figure. _e.g.  **14 (+11).**_

I think that number in parentheses has been getting added into the bonus hit point box. i.e. the one meant when for example a creature has a HD of 2+2, not in parentheses, and it would roll 2d8 and add 2 points to the total.

I just want to check that with you both @Stew-rt and @orffen that I'm reading that the right way, I don't want to go back and correct them if I'm taking that up wrong, I'm new to the system so just want to check first!  Best I know now before I've got too far into my first full pass :)

**Comment by orffen** [comment]
@totallybanjaxed I think what you're asking for is how to use these boxes?
![image](https://user-images.githubusercontent.com/2225985/190522907-8df0f50c-fc64-4225-bfad-29ff8f488c36.png)

Box A is the number of dice to roll. Box B is the bonus to be applied to the roll. So in this example, it will roll 1d8-1 HP.

Any attack bonuses should be put into the 'weapon' items on the sheet:
![image](https://user-images.githubusercontent.com/2225985/190523373-a58dfba2-40a4-4204-aab9-d41f23fe85bd.png)
![image](https://user-images.githubusercontent.com/2225985/190523697-500b4777-4069-429d-8b08-492440c06496.png)

Remember the 'weapon' can be anything - you can even just call it "Melee Weapon" or "Attack" or something if it's not specified exactly in the monster entry, and each attack can have a separate attack bonus. You could for example have a monster which has 1 claw at +2 AB, 1 claw at +0, and then 1 bite at +1, just by putting 3 separate attacks on the sheet.

**Comment by orffen** [comment]
Sorry, I just realised you may have been talking about the automatically calculated "AB" box on the monster sheet. Because that automatically calculates, you'd need to modify it using the "Bonus AB" box on the attack itself. If I'm way off base, let me know - pictures help :)

**Comment by totallybanjaxed** [comment]
@orffen cheers for the response.  It's less of a system question, more around the data side and yes pictures would have been way more helpful to you, let me correct that!  And apologies for the long winded nature of this :)

I'll use two monsters from the book for the example:
***
For the first one, the **Giant Tiger Beetle**, the HD is **3+1** as shown underlined below:
![image](https://user-images.githubusercontent.com/31042157/190592979-897609de-6500-4fe1-9756-112c0c27769b.png)

To my mind, this is what the second box in the hit dice row is meant to cover, e.g.
![image](https://user-images.githubusercontent.com/31042157/190589661-a588c94a-e986-444c-88c1-59dc98fce41e.png)
***

For the second one, the **Black Pudding**, the HD is **10 (+9)** as shown below.
![image](https://user-images.githubusercontent.com/31042157/190593360-2ca46f74-5981-49a2-a776-440b881dfb93.png)

And it's the number shown in parentheses that I'm questioning.  I think this number should **not** be added as additional hit points, as it's just a reminder that beyond 9HD, the AB value no longer matches 1 to 1 with the HD value.

So I think it should be in the compendium as this:
![image](https://user-images.githubusercontent.com/31042157/190596256-11608c97-5565-44de-9785-f7f0045b43b2.png)

as opposed to this:
![image](https://user-images.githubusercontent.com/31042157/190596474-56ba93bf-e3ed-4524-a370-bd80267bcdc4.png)

***
Because regardless, the AB is calculated fine without it during an attack roll, it gets added to the d20 roll as you'd expect:
![image](https://user-images.githubusercontent.com/31042157/190592094-f6c125e2-0378-471a-ba33-9fa8612b3a62.png)

Just wanted to get another opinion in case I'm reading the book wrong, and before I raise any further Pull Requests to update the compendium.  If you've gotten down this far, congratulations! :)

**Comment by totallybanjaxed** [comment]
For now I'm going to continue on with doing a first pass check and making any other corrections, I'll just highlight the ones that have the situation mentioned above.  I can then come back and correct all those in one go in the next pass.

**Comment by Stew-rt** [comment]
Monsters considered final.. until we get issues raised - thanks again totallybanjaxed
